-- Original price before discount (nullable). When greater than price, shown as flash deal.
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS compare_at_price NUMERIC(12, 2)
  CHECK (compare_at_price IS NULL OR compare_at_price >= 0);

INSERT INTO public.products (
  name,
  slug,
  description,
  description_fa,
  description_ar,
  description_en,
  price,
  compare_at_price,
  currency,
  stock,
  image_url,
  category_id,
  is_active
) VALUES
  (
    'Bananas (kg)',
    'bananas-kg',
    'Fresh yellow bananas sold by kilogram.',
    'موز تازه به‌ازای هر کیلوگرم.',
    'موز أصفر طازج بالكيلogram.',
    'Fresh yellow bananas sold by kilogram.',
    45000,
    60000,
    'IRR',
    120,
    '/products/bananas.png',
    (SELECT id FROM public.categories WHERE slug = 'produce' LIMIT 1),
    TRUE
  ),
  (
    'Tomatoes (kg)',
    'tomatoes-kg',
    'Vine-ripened red tomatoes sold by kilogram.',
    'گوجه فرنگی قرمز رسیده به‌ازای هر کیلوگرم.',
    'طماطم حمراء ناضجة على الكرمة بالكيلogram.',
    'Vine-ripened red tomatoes sold by kilogram.',
    32000,
    40000,
    'IRR',
    85,
    '/products/tomatoes.png',
    (SELECT id FROM public.categories WHERE slug = 'produce' LIMIT 1),
    TRUE
  ),
  (
    'Milk Full Fat 2L',
    'milk-full-fat-2l',
    'Full-fat pasteurized milk in a 2 liter bottle.',
    'شیر پرچرب پاستوریزه ۲ لیتری.',
    'حليب كامل الدسم مبستر ۲ لتر.',
    'Full-fat pasteurized milk in a 2 liter bottle.',
    65000,
    76500,
    'IRR',
    48,
    '/products/milk-2l.png',
    (SELECT id FROM public.categories WHERE slug = 'dairy' LIMIT 1),
    TRUE
  ),
  (
    'Eggs 15 Pack',
    'eggs-15-pack',
    'Farm fresh white eggs, pack of 15.',
    'تخم‌مرغ سفید تازه، بسته ۱۵ عددی.',
    'بيض أبيض طازج، عبوة ۱۵ قطعة.',
    'Farm fresh white eggs, pack of 15.',
    410000,
    480000,
    'IRR',
    36,
    '/products/eggs-15.png',
    (SELECT id FROM public.categories WHERE slug = 'dairy' LIMIT 1),
    TRUE
  ),
  (
    'Crusty Bread 500g',
    'crusty-bread-500g',
    'Golden crusty bread loaf, 500 grams.',
    'نان با پوست برشته طلایی، ۵۰۰ گرمی.',
    'رغيف خبز ذهبي مقرمش، ۵۰۰ غرام.',
    'Golden crusty bread loaf, 500 grams.',
    95000,
    110000,
    'IRR',
    64,
    '/products/bread-loaf.png',
    (SELECT id FROM public.categories WHERE slug = 'bakery' LIMIT 1),
    TRUE
  ),
  (
    'Chicken Breast 1kg',
    'chicken-breast-1kg',
    'Fresh skinless chicken breast fillets, 1 kilogram.',
    'فیله سینه مرغ بدون پوست تازه، ۱ کیلوگرم.',
    'شرائح صدر دجاج طازجة بدون جلد، ۱ كيلogram.',
    'Fresh skinless chicken breast fillets, 1 kilogram.',
    385000,
    450000,
    'IRR',
    22,
    '/products/chicken-breast.png',
    (SELECT id FROM public.categories WHERE slug = 'meat' LIMIT 1),
    TRUE
  ),
  (
    'Orange Juice 1L',
    'orange-juice-1l',
    'Fresh orange juice in a 1 liter bottle.',
    'آب پرتقال تازه ۱ لیتری.',
    'عصير برتقال طازج ۱ لتر.',
    'Fresh orange juice in a 1 liter bottle.',
    78000,
    92000,
    'IRR',
    40,
    '/products/orange-juice.png',
    (SELECT id FROM public.categories WHERE slug = 'beverages' LIMIT 1),
    TRUE
  ),
  (
    'Potato Chips 200g',
    'potato-chips-200g',
    'Classic salted potato chips, 200 gram bag.',
    'چیپس سیب‌زمینی کلاسیک، بسته ۲۰۰ گرمی.',
    'رقائق البطاطس الكلاسيكية، كيس ۲۰۰ غرام.',
    'Classic salted potato chips, 200 gram bag.',
    55000,
    65000,
    'IRR',
    90,
    '/products/potato-chips.png',
    (SELECT id FROM public.categories WHERE slug = 'snacks' LIMIT 1),
    TRUE
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  description_fa = EXCLUDED.description_fa,
  description_ar = EXCLUDED.description_ar,
  description_en = EXCLUDED.description_en,
  price = EXCLUDED.price,
  compare_at_price = EXCLUDED.compare_at_price,
  currency = EXCLUDED.currency,
  stock = EXCLUDED.stock,
  image_url = EXCLUDED.image_url,
  category_id = EXCLUDED.category_id,
  is_active = EXCLUDED.is_active;
